'use strict';

const conclusionContent = `
  <header class="chapter-opening"><p class="chapter-kicker">Conclusion</p><h2>You were not starting from zero</h2></header>
  <p class="lead">You may have opened this book believing that you needed to learn how to think like a Product Manager. More likely, you needed to recognize what you were already doing, correct a few shortcuts, and make your reasoning visible.</p>
  <p>Practical experience teaches what no glossary can replace: customers rarely describe the problem precisely; systems carry old consequences; a simple release can cost years; and a sensible decision can still produce a bad result. Terminology organizes that experience. It helps separate adoption from activation, a feature request from the underlying problem, and an opinion from a hypothesis. The name does not create the judgment.</p>
  <p>Frameworks have a place too. The seven questions prevent jumps. A prioritization model exposes assumptions. An experiment brief combines success and risk before results create pressure. The ninety-second structure makes an interview answer navigable. None of these decides how much risk to accept, which customer to serve, or when evidence is sufficient.</p>
  <h3>Seniority is decision quality</h3><p>Seniority does not mean permanent certainty. It means noticing which gap matters, calibrating evidence to reversibility, recommending a choice, owning the trade-off, and creating a learning mechanism. It means saying no without dismissing the signal, saying yes without hiding the cost, and changing direction without rewriting history.</p>
  <p>When someone asks how you would prioritize an enterprise request, you can begin with intuition: “I need to know whether similar customers experience it and what we would stop doing.” You can now make the structure explicit: validate the pattern in the ICP, estimate revenue at risk, assess strategic fit, total cost, confidence, and opportunity cost, then choose the smallest useful test and define a decision rule.</p>
  <aside class="callout takeaway"><strong>The idea to keep.</strong> The goal is not to look like a Product Manager. It is to make existing reasoning explicit, shareable, and improvable. Language gives it form. Evidence gives it resistance. Judgment gives it direction.</aside>
  <p class="closing-line">You were not starting from zero. You were learning to name the path.</p>`;

const CHAPTER_NOTEBOOKS = {
  'capitulo-1': `<section class="field-notes"><h3>In practice: the agenda behind the agenda</h3><p>Consider an ordinary week. Support reports rising tickets, Sales brings a request from a large account, Engineering finds a constraint, and leadership asks why the roadmap changed. Product creates a decision line between these events. Do the tickets represent a recurring problem or customer-base growth? Does the enterprise request protect strategy or displace it? Does the technical limit kill the thesis or merely change the test?</p><p>A short decision log helps. Record context, evidence, assumptions, options, decision, trade-off, owner, and review date. It is not meeting minutes. It preserves the logic so a bad outcome does not turn a reasonable decision into an “obvious mistake,” and luck does not make a weak decision look strong.</p><aside class="callout framework"><strong>Operating questions.</strong> Which decision must happen? Who has authority? Which information could reverse it? What does waiting cost? When will it be revisited?</aside></section>`,
  'capitulo-2': `<section class="field-notes"><h3>Use depth in proportion to risk</h3><p>Changing button copy may require five minutes across the seven questions. Replacing a pricing model may require weeks of commercial analysis, cohorts, interviews, modeling, and rollout planning. The questions remain; the cost of answering them changes with reversibility and damage.</p><p>The order can change too. During a billing incident, risk measurement and rollback come before complete discovery. After stabilization, the team returns to audience, evidence, and cause. In an exploratory bet, the target audience may itself remain uncertain. Write the uncertainty instead of pretending it is resolved.</p><aside class="callout interview"><strong>In an interview.</strong> Do not recite all seven questions. Start with the two gaps most capable of changing the case, advance with explicit assumptions, and return to the full structure when recommending and measuring.</aside></section>`,
  'capitulo-3': `<section class="field-notes"><h3>Deconstruct a request without dismissing the requester</h3><p>Customers know processes, political consequences, buying criteria, and alternatives that the product team may not know. They do not see the complete architecture, other segments, and opportunity cost. A productive conversation preserves their authority over the problem and shares exploration of the solution.</p><p>A request can become a general capability, an integration, a temporary service, or a deliberate “not now.” Close the loop in every case. A bare no encourages political escalation; an explanation with evidence and an alternative improves the next signal.</p><aside class="callout example"><strong>Useful sentence.</strong> “The requested format is one option. Before committing to it, I want to understand the decision this report supports and whether a configurable capability can solve this and other cases without exclusive maintenance.”</aside></section>`,
  'capitulo-4': `<section class="field-notes"><h3>Map value and power separately</h3><p>Draw two flows. In the value flow, an end user completes a task, a manager gains visibility, and the company reduces cost. In the power flow, Security can veto, Finance controls budget, and Procurement defines conditions. A product can win in the first flow and lose in the second.</p><p>In PLG, entry may come through a user who is also a low-risk buyer. As the account grows, admins, procurement, and an economic buyer appear. That transition creates governance needs and a product-led sales signal. Recognizing it without damaging self-service is a strategic capability.</p><aside class="callout framework"><strong>Minimum role profile.</strong> Job, frequency, incentive, pain, power, available information, successful behavior, and conflict with other roles.</aside></section>`,
  'capitulo-5': `<section class="field-notes"><h3>From vocabulary to a decision sentence</h3><p>Definition recall is not mastery. Mastery appears when a term changes the decision. Translate it into ordinary language, connect it to experience, and use it in a recommendation. Opportunity cost becomes “the value of what we stop doing”; the experience is delaying onboarding to build export; the recommendation explains why that exchange is or is not acceptable.</p><p>Terms often seem similar because they exist at different levels. An initiative is a bet; an epic groups delivery. An outcome is a change; an output is an artifact. A hypothesis is testable; an assumption supports it. An MVP delivers real value; a prototype represents an experience; a proof of concept tests technology.</p><aside class="callout exercise"><strong>Practice.</strong> Select ten terms. For each, record a twenty-second sentence containing context, the term, and a decision. If the sentence works better without the term, do not force it.</aside></section>`,
  'capitulo-6': `<section class="field-notes"><h3>Operational definitions before charts</h3><p>Every metric needs an event, population, window, and rule. “Retention improved” is incomplete. “The proportion of January agency accounts completing at least one weekly close between weeks five and eight increased versus the previous three cohorts” can be audited.</p><p>Choosing the event is a product decision. Login is easy to count but can represent forced work rather than value. Look for behavior connected to the job: a report used, a project closed, an order processed. Connect financial metrics to behavioral cohorts because price increases and annual contracts can hide declining product quality.</p><aside class="callout framework"><strong>Metric contract.</strong> Name, question answered, definition, source, owner, frequency, segments, limitations, and expected action.</aside></section>`,
  'capitulo-7': `<section class="field-notes"><h3>Build the causal chain backward</h3><p>If the outcome is team retention, ask why a team would stay. Perhaps complete data enables accurate billing. That requires consistent entries, which require invitations, project setup, and a successful first record. Each link suggests a leading indicator. Choose one close enough to the intervention and meaningfully connected to the outcome.</p><p>The chain is a hypothesis, not a law. Motivated users may complete every step and retain for unrelated reasons. Compare cohorts, run experiments when practical, and use interviews to distinguish mechanism from correlation.</p><aside class="callout example"><strong>Scenario.</strong> Objective: expansion in PLG accounts. Leading: reach ten active users. Lagging: upgrade within sixty days. Guardrails: removals after invitation, billing complaints, and contributor retention.</aside></section>`,
  'capitulo-8': `<section class="field-notes"><h3>An ICP is a strategic hypothesis</h3><p>An ICP does not emerge from a brainstorming session. It combines evidence about need, retention, economics, acquisition, and ability to serve. Begin with accounts obtaining recurring value; examine the job, operating environment, and buying path; then ask whether the company wants and can build an advantage there.</p><p>Fit changes with maturity. An e-commerce product may begin with founder-operated stores and later discover agencies managing dozens of stores. The new segment may retain and expand better while requiring permissions and more complex Support. Choosing it is a product and operating-model decision, not merely a market label.</p><aside class="callout error"><strong>Misleading diagnosis.</strong> “Enterprise does not use it” may mean admins never completed setup. “SMB loves it” may mean a few vocal power users. Connect segment, exposure, activation, and retention.</aside></section>`,
  'capitulo-9': `<section class="field-notes"><h3>Create an evidence plan</h3><p>Before opening dashboards or scheduling interviews, write the decision and minimum evidence. To decide whether search deserves investment, learn who searches, their intent, whether results are found, the consequence of failure, and whether the problem belongs to the ICP. Logs provide volume; sessions show reformulation; interviews reveal the job; tickets show severity.</p><p>Mark source, date, segment, and independence. Ten tickets from one account after an incident are not ten patterns. Copied Sales notes are not independent interviews. Discovery should end for a decision: you may know enough to invest one week without knowing enough to invest one quarter.</p><aside class="callout framework"><strong>Confidence.</strong> Low: indirect signals. Medium: independent sources converge in the predicted audience. High: behavior and consequence are observed at useful breadth and depth. None means certainty.</aside></section>`,
  'capitulo-10': `<section class="field-notes"><h3>An interface between Sales and Product</h3><p>A signal record should capture account, ICP, stage, potential value, job, consequence, alternative, and evidence that the barrier changed the purchase. Do not ask sellers to perform complete research. Ask for enough context to group signals and choose where Product should go deeper.</p><p>Review patterns, not every request. Show independent signals, segments, stage, revenue at risk, learning, and decision. Then close the loop: explore, provide a workaround, recruit design partners, build, or decline. Measure false positives by checking whether prospects who claimed a blocker actually purchased and adopted after it was removed.</p><aside class="callout interview"><strong>In an interview.</strong> Do not portray Sales as a source of bad requests. Recognize incentives, propose an evidence system, and still decide the case.</aside></section>`,
  'capitulo-11': `<section class="field-notes"><h3>Moderation is a product skill</h3><p>Do not rush to fill silence. People often remember details after a pause. Ask for sequence before interpretation, and use neutral probes such as “What happened next?” or “What made that difficult?” Avoid praise that trains participants to confirm your preferred direction.</p><p>Recruit intentionally. If the decision concerns failed onboarding, interview successful users, people who attempted and stopped, and eligible people who never began. Existing power users cannot explain every entry barrier. Stop interviews when new sessions stop changing the decision, not at a ceremonial number.</p><aside class="callout exercise"><strong>Interview note.</strong> Separate observed fact, participant interpretation, your interpretation, and the next question. Mixing them turns research into confirmation.</aside></section>`,
  'capitulo-12': `<section class="field-notes"><h3>Assumption mapping without theater</h3><p>Ask “What must be true for this bet to work?” Engineering reveals dependencies, Sales and CS reveal purchase conditions, Design reveals comprehension, and Product connects behavior and economics. Place each belief by uncertainty and damage if wrong. Test the high-high quadrant first.</p><p>List competing hypotheses. Abandonment can come from complexity, missing data, low fit, or exploratory intent. Define which observation would distinguish them. A fake door can test interest but not trust, technical feasibility, or operational viability.</p><aside class="callout framework"><strong>Format.</strong> We believe [segment] will [behavior] after [intervention] because [mechanism]. We will know through [measure] and reconsider if [contrary evidence].</aside></section>`,
  'capitulo-13': `<section class="field-notes"><h3>Make exceptions explicit</h3><p>When a large account deserves special work, record the reason, scope, owner, maintenance path, and exit condition. An exception can be rational and still create debt. Visibility prevents the temporary solution from silently becoming product architecture.</p><p>Concentration risk changes negotiation. Losing a customer worth 18% of ARR may require immediate protection, but it also reveals strategic fragility. The short-term choice should not prevent a long-term plan to reduce dependency.</p><aside class="callout framework"><strong>Decision frame.</strong> Revenue genuinely at risk, recurrence in the ICP, strategic capability, total lifecycle cost, concentration, opportunity cost, and reversibility.</aside></section>`,
  'capitulo-14': `<section class="field-notes"><h3>Compare consequences, not adjectives</h3><p>“Critical,” “strategic,” and “high impact” are conclusions. Replace them with observable statements. “Blocks weekly billing for 35% of agency accounts” creates a comparison. “Very important to customers” does not.</p><p>Run a sensitivity check before trusting a rank. Which estimate drives the result? If reach fell by half or effort doubled, would the choice change? When small changes reverse the order, confidence should be low and sequencing should favor learning.</p><aside class="callout error"><strong>Common failure.</strong> Parallelizing three urgent initiatives that require the same specialists. A roadmap can show parallel rows while reality remains sequential.</aside></section>`,
  'capitulo-15': `<section class="field-notes"><h3>One roadmap, different audiences</h3><p>Leadership needs outcomes, investment, and risk. Engineering needs sequence and dependencies. Sales needs commitment confidence. Customers need direction without fiction. Adapt the layer, not the truth.</p><p>Distinguish a target, a planning window, and a promise. Dates are legitimate for campaigns, contracts, and migrations. The error is giving an uncertain bet and a firm obligation the same appearance. Publish decision changes with new evidence, impact, and the next checkpoint.</p><aside class="callout framework"><strong>Review.</strong> Is the outcome still valid? Did evidence change? Did confidence rise? Is this still the best investment? Which commitments require communication?</aside></section>`,
  'capitulo-16': `<section class="field-notes"><h3>A complexity budget</h3><p>Every option consumes an invisible budget. Users pay with attention; Engineering with states; Support with explanation; Product with future capacity. Products that spend this budget without removing old complexity become incoherent.</p><p>Before adding configuration, ask whether a strong default solves most cases. Before another report, look for configurable components. Review features without an owner, use, or protected outcome. Removal requires care, but recovering coherence reduces Support cost and accelerates future work.</p><aside class="callout exercise"><strong>Premortem.</strong> “One year from now, why do we regret adding this?” List maintenance, interpretation, mobile, documentation, analytics, and removal before accepting the initial estimate.</aside></section>`,
  'capitulo-17': `<section class="field-notes"><h3>Use fidelity in the dimension being tested</h3><p>Write the uncertainty before choosing the method. “Will managers act on alerts?” calls for a concierge with real alerts. “Can they configure it?” calls for a prototype. “Can the calculation scale?” calls for a proof of concept. Building an MVP for every question wastes information.</p><p>For pricing, the economic consequence must be credible. For usability, important states must exist. For feasibility, data and load must be realistic. A visually perfect flow with fake data does not test performance.</p><aside class="callout framework"><strong>Sequence.</strong> Critical risk → behavior → realistic environment → evidence → cost → decision.</aside></section>`,
  'capitulo-18': `<section class="field-notes"><h3>A brief is a contract with your future self</h3><p>Before results exist, ambiguity feels harmless. Afterward, it becomes permission to tell any story. Write who is eligible, who is exposed, which event represents value, how long the window lasts, and what damage forces a stop.</p><p>Not every test supports statistical inference. Small B2B samples may need behavioral depth, operational evidence, and reversible decisions. Be explicit about what the design cannot establish. “Three design partners completed the workflow” is useful evidence and not proof of market-wide conversion.</p><aside class="callout error"><strong>Common failure.</strong> Choosing an MDE because 10% sounds clean. Begin with the smallest improvement that changes the economic decision, then ask whether the available sample can detect it.</aside></section>`,
  'capitulo-19': `<section class="field-notes"><h3>Read the chain, not one number</h3><p>If exposure rises but attempts do not, relevance or discoverability may be weak. If attempts rise but completion does not, usability or feasibility may be broken. If activation rises but retention does not, the activation event may not represent durable value.</p><p>Segment before averaging. An enterprise workflow can be highly valuable and irrelevant to self-service. The question is not whether the combined average is positive. It is whether the differentiated behavior supports the chosen strategy and operating model.</p><aside class="callout framework"><strong>Decision record.</strong> Observed result, strongest explanation, competing explanation, affected segment, uncertainty remaining, action, owner, and review window.</aside></section>`,
  'capitulo-20': `<section class="field-notes"><h3>Operate the learning</h3><p>Create a table with signal, source, owner, frequency, and action. Critical errors alert in minutes; Support themes may be reviewed daily; activation weekly; retention only after maturation. Monitoring frequency should match the speed of risk.</p><p>Prepare Support with the problem, audience, change, limitations, and tags. Prepare Sales with value and eligibility without turning a beta into a promise. A progressive rollout needs a real pause mechanism, a tested rollback, and a plan for affected accounts.</p><aside class="callout framework"><strong>Post-launch record.</strong> Problem, hypothesis, scope, exposure, outcome, guardrails, incidents, segments, decision, debt, and next steps.</aside></section>`,
  'capitulo-21': `<section class="field-notes"><h3>The hidden rubric</h3><p>Interviewers often score observable behaviors: whether you clarified the objective, segmented the audience, selected evidence, made a recommendation, acknowledged consequences, and connected measures to a decision. They cannot score good instincts that never become visible.</p><p>Calibrate depth. Offer a clear spine first, then expand where the interviewer probes. Dumping every framework creates cognitive load and can signal that you have not identified the central tension.</p><aside class="callout interview"><strong>Self-check.</strong> Could the interviewer write your problem frame, criteria, recommendation, and trade-off in four lines? If not, the answer is probably too diffuse.</aside></section>`,
  'capitulo-22': `<section class="field-notes"><h3>Ask questions with decision value</h3><p>A useful clarification can change the action. “Is the drop concentrated in the ICP?” may reverse priority. “Can you tell me more?” merely requests volume. Ask at most a few high-value questions, then state assumptions and proceed.</p><p>Conditional recommendations are still recommendations. “Assuming the issue began after release and affects payment, I would pause rollout now; if it predates the release and is concentrated in low-fit traffic, I would continue while investigating acquisition quality.” The condition is explicit and the action is visible.</p><aside class="callout error"><strong>Common failure.</strong> Building so many branches that no decision survives. Show the primary path and the evidence that would make you switch.</aside></section>`,
  'capitulo-23': `<section class="field-notes"><h3>Deliberate practice</h3><p>Create cards with a scenario on the front and the five-step spine on the back. Answer without reading. Record yourself and ask: was the problem clear, would the questions change the decision, were criteria visible, did I recommend, and did measures trigger follow-up?</p><p>Compress to forty-five seconds and expand to five minutes. The short version reveals the essence; the long version tests depth. Prepare personal examples for discovery, trade-offs, conflict, failure, influence, and results. Do not turn every story into a victory.</p><aside class="callout exercise"><strong>Scoring.</strong> Give zero to two points for each of the five steps. Below seven, change the structure before trying to speak faster.</aside></section>`,
  'capitulo-24': `<section class="field-notes"><h3>Use contrast to improve judgment</h3><p>A weak answer often contains a reasonable activity but no decision logic. “Talk to customers” can be useful; it becomes strong only when the audience, question, evidence, and consequence are specified.</p><p>After comparing the examples, rewrite the excellent answer in your own words. Memorizing model language creates brittle performance. Preserving the causal structure creates transfer to unfamiliar scenarios.</p><aside class="callout interview"><strong>Practice rule.</strong> Answer first, compare second, rewrite third. Reading the model before attempting the case trains recognition, not retrieval.</aside></section>`,
  'capitulo-25': `<section class="field-notes"><h3>Precision without performance</h3><p>Replace adjectives with criteria. “Important customer” becomes “18% of ARR, renewal in sixty days, and strong ICP fit.” “Small experiment” becomes “a two-week concierge test with five eligible accounts.”</p><p>Replace activity with intent. “Analyze data” becomes “compare cohorts to locate whether decline begins before activation.” Replace certainty with calibrated confidence: “Confidence is medium because stated need and behavior converge; a limited rollout protects the remaining risk.”</p><aside class="callout exercise"><strong>Revision.</strong> Delete “strategic,” “impactful,” and “data-driven” from an answer. Add each word back only when you can identify the choice, impact, or data it refers to.</aside></section>`,
  'capitulo-26': `<section class="field-notes"><h3>The map is recursive</h3><p>Each box can send the team backward. Weak evidence may require a narrower segment. A failed test may reveal a different underlying problem. A guardrail breach may expose a stakeholder absent from the original map. Recursion is learning, not failure.</p><p>Use the map to diagnose stuck conversations. If the team argues about scope, perhaps the outcome is unclear. If it debates metrics, perhaps the causal mechanism is missing. If every request seems urgent, perhaps strategy has not selected an ICP or outcome.</p><aside class="callout framework"><strong>Fast diagnosis.</strong> Name the current box, the unresolved question, the evidence needed, the decision owner, and the next time the group will decide.</aside></section>`,
  'capitulo-27': `<section class="field-notes"><h3>A living checklist</h3><p>Add items after recurring failures, not after every opinion. If the team repeatedly forgets exposure, make it mandatory. If pricing never appears in the decision, do not enlarge the ritual.</p><p>For quick reversible choices, use the pocket version. For irreversible decisions, add a premortem, adverse scenario, Legal, Security, and operations. Record why an item was ignored. A checklist informs judgment; it does not govern by unanimity.</p><aside class="callout exercise"><strong>Application.</strong> Complete the checklist for one active initiative and find the single missing answer most capable of reversing the decision.</aside></section>`,
  'capitulo-28': `<section class="field-notes"><h3>Build fluency through relationships</h3><p>Group terms by decision. Discovery connects evidence, hypothesis, and value risk. Prioritization connects impact, confidence, and opportunity cost. Metrics connect activation, retention, and guardrails. Delivery connects scope, dependency, rollout, and rollback.</p><p>When a company uses a term differently, do not correct it performatively. Ask for the operational definition: “When we say activation here, which behavior and window do we mean?” Local language can vary; the decision still needs shared meaning.</p><aside class="callout takeaway"><strong>Final test.</strong> Explain a term in ordinary language, give a real example, contrast it with a neighboring concept, and name one misuse. If you can, the term has become a tool.</aside></section>`
};

const interviewCases = [
  {q:'An important feature has low adoption. What do you do?',weak:'I would talk to users and improve promotion.',why:'It assumes an awareness problem and does not define the eligible audience.',good:'I would separate eligible, exposed, attempted, and adopting users, inspect the funnel, and interview people in each group.',excellent:'First I would define the segment and the value-producing behavior. I would compare exposure, first attempt, activation, and repeated use by cohort. Low exposure suggests discovery; attempts without completion suggest usability; completion without repetition suggests weak recurring value. I would test the smallest intervention at the largest break, using retention and Support as guardrails.',terms:'eligible users, adoption funnel, activation, retention, guardrail',short:'Diagnose whether the gap is awareness, usability, or value before choosing an intervention.'},
  {q:'Support tickets increased after a release. What do you do?',weak:'I would ask Engineering to fix the feature.',why:'It treats correlation as cause and ignores base growth and severity.',good:'I would normalize tickets by exposure, classify themes, and compare pre-release behavior.',excellent:'I would first identify critical incidents and pause rollout if necessary. Then I would normalize tickets per exposed account, separate defects, confusion, and expected questions, and compare affected segments and versions. A clear regression triggers rollback or a focused fix; increased use with low-severity questions may call for guidance. The decision depends on damage, reversibility, and whether the primary outcome still improves.',terms:'exposure, severity, baseline, rollout, rollback',short:'Protect users first, then distinguish regression from increased usage and learning cost.'},
  {q:'A large enterprise customer requests a feature. Do you prioritize it?',weak:'Yes, because it is the largest customer.',why:'Revenue becomes the only criterion and opportunity cost disappears.',good:'I would assess revenue at risk, broader demand, strategic fit, and effort.',excellent:'I would verify the commercial consequence, recurrence within the ICP, generalizability, total lifecycle cost, concentration risk, and the initiative displaced. If the request protects material revenue and builds a strategic capability, I would explore it with a bounded design partnership. If it is a permanent exception, I may offer a temporary service or decline while protecting the relationship.',terms:'revenue at risk, ICP, strategic fit, concentration risk, opportunity cost',short:'Customer size changes the weight of the request; it does not end the analysis.'},
  {q:'Team capacity drops by thirty percent. How do you respond?',weak:'I would ask everyone to work faster and move the dates.',why:'It distributes delay without protecting an outcome.',good:'I would reprioritize the roadmap and communicate the impact.',excellent:'I would separate commitments, incidents, and discretionary bets, then identify the shared constrained capability. I would protect the highest-cost obligations and central outcome, reduce scope where value survives, resequence dependencies, and explicitly stop work. Stakeholders would receive the new sequence, accepted consequences, and review point rather than fictional parallel dates.',terms:'capacity constraint, commitment, scope reduction, sequencing, trade-off',short:'Protect outcomes and obligations, reduce or stop work, and communicate consequences.'},
  {q:'Design and Engineering disagree about a solution.',weak:'I would schedule a meeting until they agree.',why:'It seeks consensus without locating the disagreement.',good:'I would return to the problem and success criteria.',excellent:'I would separate facts, preferences, and constraints. Design may be protecting comprehension while Engineering protects performance or time. I would restate audience, outcome, and risks, identify the assumption distinguishing the options, and test it through a prototype or spike when possible. Otherwise, the decision owner chooses against explicit criteria and defines how the unresolved risk will be monitored.',terms:'decision criteria, usability risk, feasibility risk, decision owner',short:'Locate the underlying assumption, test it if possible, then decide against shared criteria.'},
  {q:'Trial users are not reaching value.',weak:'I would redesign onboarding.',why:'It chooses a solution before locating the break.',good:'I would analyze the onboarding funnel and interview drop-offs.',excellent:'I would define first value for the target segment and map eligibility, exposure, setup, activation, and time to value. I would compare successful and unsuccessful cohorts, observe recent sessions, and separate missing data, comprehension, effort, and weak fit. The first test would target the dominant mechanism; retention and error volume would guard against making activation artificially easy.',terms:'time to value, activation, funnel, cohort, value risk',short:'Define first value, locate the break, and test the mechanism rather than redesigning everything.'},
  {q:'Sales says a missing feature is blocking several deals.',weak:'I would put it on the roadmap because Sales is closest to prospects.',why:'It treats statements as independent verified losses.',good:'I would ask for account context and validate the pattern.',excellent:'I would capture segment, stage, deal value, underlying job, alternatives, and evidence that the feature changed the purchase. I would check whether signals are independent, whether existing users show the same problem, and whether a general capability supports strategy. I would return a decision and rationale to Sales, then verify whether resolved objections actually convert and adopt.',terms:'Sales objection, pattern validation, pipeline, product strategy',short:'Turn commercial claims into comparable evidence and close the learning loop.'},
  {q:'Leadership wants to monetize a popular capability quickly.',weak:'I would add a paywall and run an A/B test.',why:'It chooses a mechanism without understanding differentiated value or retention risk.',good:'I would assess usage and willingness to pay before testing price.',excellent:'I would clarify whether the objective is immediate revenue, ARPA, qualification, or packaging. I would identify who receives differentiated value, how frequently, and how the capability supports acquisition. Then I would compare an add-on, usage limit, higher tier, or strategic inclusion. Any pricing test would include activation, retention, and Support guardrails so a short-term conversion win does not damage the growth engine.',terms:'pricing, packaging, paywall, expansion revenue, guardrail',short:'Clarify the revenue objective and test packaging without damaging activation or retention.'},
  {q:'Retention has stopped improving. What do you investigate?',weak:'I would add more engagement features.',why:'It assumes frequency creates value and ignores segment and cohort maturity.',good:'I would compare retained and churned cohorts and interview both.',excellent:'I would confirm the retention definition and window, then segment by ICP, acquisition source, activation path, and product behavior. I would identify behaviors preceding retention without assuming causality and investigate churn episodes for mechanism. The next intervention would target the strongest value break, not engagement in general, and would be evaluated on mature cohorts.',terms:'retention, cohort, segmentation, activation, churn',short:'Find where durable value breaks by segment and activation path before adding engagement.'},
  {q:'The primary metric improves but a guardrail worsens.',weak:'The experiment succeeded because the main metric won.',why:'It treats the guardrail as decoration.',good:'I would compare the size of the gain and the harm.',excellent:'I would apply the threshold and decision rule agreed before the test. A breached safety or financial guardrail can require rollback regardless of the average gain. For softer limits, I would segment the harm, test whether a specific correction can preserve the mechanism, and state the accepted trade-off. I would not move the guardrail after seeing a favorable primary result.',terms:'primary metric, guardrail metric, decision rule, rollback criteria',short:'Honor the pre-agreed limit, locate the harm, and decide whether it is correctable or unacceptable.'},
  {q:'You receive three urgent initiatives. How do you choose?',weak:'I would use RICE and take the highest score.',why:'It outsources judgment before separating obligations and bets.',good:'I would compare impact, confidence, effort, and strategic fit.',excellent:'First I would classify incidents, commitments, and discretionary bets. Then I would compare them with the same criteria: user and business impact, cost of delay, strategic alignment, confidence, effort, risk, dependencies, and reversibility. I would test sensitivity and present a sequence showing what starts, what waits, and which consequence we accept.',terms:'cost of delay, confidence, dependency, reversibility, trade-off',short:'Classify obligations versus bets, compare shared criteria, and make sequencing consequences explicit.'},
  {q:'A feature is cheap but outside strategy.',weak:'I would build it because it only takes two days.',why:'It ignores lifecycle cost, precedent, and displaced focus.',good:'I would compare value with total cost and strategic fit.',excellent:'I would verify the user problem, reach, and whether the capability creates a reusable primitive or an exception. Total cost includes design, QA, Support, documentation, analytics, maintenance, cognitive load, and removal. If value remains local and the feature weakens product coherence, I would decline or use a temporary workaround despite the low build estimate.',terms:'total cost, strategic fit, product coherence, opportunity cost',short:'A short build estimate does not make a low-fit lifecycle cheap.'},
  {q:'Users request a specific solution repeatedly.',weak:'I would build the most requested solution.',why:'Frequency of a proposed answer does not establish one underlying problem.',good:'I would investigate the job and current workaround.',excellent:'I would reconstruct recent episodes, identify who performs the job, and separate shared consequence from familiar solution language. Then I would quantify recurrence in the target segment and compare alternatives against value, usability, feasibility, and viability. The requested solution remains an input, not the specification.',terms:'Jobs to be Done, workaround, pattern validation, product risk',short:'Respect repeated demand, but validate the underlying job before selecting the solution.'},
  {q:'Stakeholders disagree about priority.',weak:'I would align everyone and seek consensus.',why:'It hides conflicting objectives and decision rights.',good:'I would agree on criteria and compare the options.',excellent:'I would surface each stakeholder’s objective, evidence, constraint, and risk, then restate the company outcome and decision owner. We would compare the same options on shared criteria and name which consequence each choice creates. Input should be broad; accountability for the decision should be clear. Alignment means understanding the choice, not unanimous preference.',terms:'stakeholder, decision rights, strategic alignment, trade-off',short:'Expose objectives and decision rights, compare shared criteria, and make one accountable choice.'},
  {q:'An experiment is inconclusive. What do you do?',weak:'I would run it longer until the result is significant.',why:'More time does not repair a weak design or uninformative signal.',good:'I would review sample, instrumentation, and effect size.',excellent:'I would ask whether the result is inconclusive because of low volume, noisy measurement, heterogeneous segments, implementation failure, or a genuinely small effect. I would verify exposure and guardrails, then estimate the value of more information. If a specific redesign can distinguish competing explanations at reasonable cost, I would iterate. Otherwise I would stop or make the smallest reversible decision supported by current evidence.',terms:'minimum detectable effect, instrumentation, segmentation, value of information',short:'Diagnose why the result is inconclusive before buying more time.'}
];

function interviewCasesHtml() {
  return interviewCases.map((x,i) => `<article class="interview-case"><p class="case-number">Case ${String(i+1).padStart(2,'0')}</p><h3>${x.q}</h3><div class="answer weak"><h4>Weak answer</h4><p>${x.weak}</p><p><strong>Why it is weak:</strong> ${x.why}</p></div><div class="answer good"><h4>Good answer</h4><p>${x.good}</p></div><div class="answer excellent"><h4>Excellent answer</h4><p>${x.excellent}</p></div><p><strong>Terms:</strong> ${x.terms}.</p><p><strong>Compressed version:</strong> ${x.short}</p></article>`).join('');
}

BOOK_PARTS.push(
  {
    id: 'parte-5', title: 'Part V — Experimentation and delivery', chapters: [
      { id: 'capitulo-17', number: 17, title: 'What is the smallest thing we can do?', content: `
        <p class="lead">“Smallest” does not mean fewer screens. It means the lowest-cost investment that reduces the most important uncertainty with evidence reliable enough for the next decision.</p>
        <dl class="experiment-ladder"><div><dt>Research</dt><dd>Interviews, analysis, and observation used to understand the problem and context. It does not measure reaction to a real solution.</dd></div><div><dt>Prototype</dt><dd>A clickable or physical representation used to test comprehension and flow.</dd></div><div><dt>Concierge test</dt><dd>The team manually delivers value while the customer understands the operation.</dd></div><div><dt>Fake door</dt><dd>A visible entry measures interest before the capability exists and honestly explains its absence.</dd></div><div><dt>Wizard of Oz</dt><dd>The experience appears automated while the operation behind it is manual.</dd></div><div><dt>MVP</dt><dd>The smallest functional product that delivers real value and tests sustainable use.</dd></div><div><dt>Beta</dt><dd>A real version for a controlled audience with an expectation of change.</dd></div><div><dt>Limited rollout</dt><dd>A progressive release by percentage or segment used to control risk.</dd></div><div><dt>Full release</dt><dd>Broad availability with mature operations, Support, and monitoring.</dd></div></dl>
        <p>Choose by risk. If Finance may not value automatic reports, a weekly concierge tests value. If the workflow is desired but complex, a prototype tests usability. If processing at scale is uncertain, use a proof of concept. If failure can affect billing, use a limited rollout with rollback.</p>
        <p>An MVP is not a poor first release. If removing a component prevents users from receiving value, you did not reduce scope; you removed the validity of the test. A manual solution may be smaller and more informative than partial software.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Building a small version of every component. That spreads investment and may test no critical assumption.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Identify what could make the bet wrong and buy the cheapest evidence capable of changing your decision.</aside>` },
      { id: 'capitulo-18', number: 18, title: 'Define success before you build', content: `
        <p class="lead">Defining success in advance protects the team from later rationalization. An experiment brief should be short enough to read and specific enough to produce a decision.</p>
        <div class="experiment-brief"><h3>Experiment brief</h3><p><strong>Problem:</strong> admins of remote teams take days to complete the first workflow because adding members is manual.</p><p><strong>Target segment:</strong> B2B trials with 20–100 seats and an employee file available.</p><p><strong>Hypothesis:</strong> validated CSV import will increase the proportion completing the first workflow within twenty-four hours.</p><p><strong>Primary metric:</strong> twenty-four-hour activation among eligible accounts.</p><p><strong>Leading indicator:</strong> import started and completed.</p><p><strong>Guardrail:</strong> member errors, Support tickets, and removals within forty-eight hours.</p><p><strong>Minimum detectable effect:</strong> the smallest improvement that justifies cost and complexity, defined from a real baseline and volume.</p><p><strong>Duration:</strong> enough complete business cycles and planned volume, not merely a convenient date.</p><p><strong>Kill criteria:</strong> low completion after two focused iterations or recurring damage.</p><p><strong>Rollback criteria:</strong> a critical data error or guardrail above its threshold.</p><p><strong>Decision rule:</strong> scale if activation improves and guardrails hold; iterate if the leading signal rises without activation; rollback if harm appears.</p></div>
        <p>The minimum detectable effect should not be a ritual number. Ask which improvement would pay for the investment and matter to the business. Then check whether available volume can observe it in useful time. When it cannot, combine evidence and keep the decision reversible.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Choosing duration after looking at the chart and ending at a favorable peak.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> A brief connects problem, audience, hypothesis, measure, protection, and decision. A blank section reveals discovery still required.</aside>` },
      { id: 'capitulo-19', number: 19, title: 'Iterate, scale, or rollback', content: `
        <p class="lead">Results rarely arrive as a clean success or failure. Senior interpretation preserves the causal chain, examines segments, and chooses which uncertainty deserves more investment.</p>
        <div class="diagram decision-flow" aria-label="Iterate, scale, or rollback flow"><div class="node">Result</div><div class="branches"><div><span>Outcome improves<br>guardrails stable</span><strong>Scale</strong></div><div><span>Partial signal<br>correctable cause</span><strong>Iterate</strong></div><div><span>Harm or thesis refuted</span><strong>Rollback / Kill</strong></div></div></div>
        <h3>Common scenarios</h3><p><strong>Activation rises, retention does not:</strong> wait for the correct window, then question whether activation represents value or merely easy completion. <strong>Conversion rises, tickets increase:</strong> normalize and classify. The cause may be more customers, a misleading promise, or post-purchase friction. <strong>Adoption is low, satisfaction is high:</strong> a valuable niche, poor discovery, or a small eligible audience may exist.</p>
        <p><strong>Usage is high, revenue does not change:</strong> the capability may protect retention, or usage may not produce willingness to pay. Examine expansion, churn, and packaging. <strong>Enterprise usage is high, self-service usage is low:</strong> do not average. The capability may support governance while remaining irrelevant to PLG.</p>
        <h3>Decision rules</h3><p><strong>Scale</strong> when effect, confidence, operation, and strategy support expansion. <strong>Iterate</strong> when the core thesis remains plausible and a specific change can address the break. <strong>Rollback</strong> when harm exceeds benefit. <strong>Kill</strong> when the critical hypothesis is refuted or the cost of more information exceeds its value.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Iterating automatically because investment has already occurred. Sunk cost does not increase the probability of success.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Interpret the system, not one green arrow. Ambiguous results require an explicit next decision, not indefinite monitoring.</aside>` },
      { id: 'capitulo-20', number: 20, title: 'Launch is not the end of the work', content: `
        <p class="lead">Launch changes the nature of uncertainty. Before launch, the question is whether the idea can work. After launch, the team can observe for whom it works, under which conditions, at what cost, and for how long.</p>
        <h3>Before release</h3><p>Instrumentation should capture exposure, value events, errors, and segment. Monitoring needs an owner, frequency, and thresholds. Rollout defines account sequence, flags, and pauses. Support needs context, risk signals, and an escalation path. Without these, the team launches and later tries to reconstruct what happened.</p>
        <h3>Feedback loops</h3><p>Combine telemetry, tickets, interviews, and operational evidence. Data points to where to look; accounts explain mechanisms; technical logs expose failures; Sales reveals changes in the commercial conversation. Hold a post-launch review after the appropriate outcome window.</p>
        <p>A useful review records the original hypothesis, scope changes, exposed audience, result against baseline, guardrails, segment differences, incidents, learning, and decision. Update documentation and analytics so future teams can recover why the bet existed.</p>
        <h3>Segmentation and rollout</h3><p>Begin with design partners when the goal is deep feedback, a small random percentage when estimating a broad effect, and a specific segment when value or risk is localized. Do not extrapolate enterprise behavior to self-service without evidence.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Measuring adoption across all users. Include eligibility and exposure; no one adopts what they cannot see or use.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Delivery ends when software is operable. Product learning ends when evidence changes a decision and becomes available to future work.</aside>` }
    ]
  },
  {
    id: 'parte-6', title: 'Part VI — Product Management interviews', chapters: [
      { id: 'capitulo-21', number: 21, title: 'What an interview is actually evaluating', content: `
        <p class="lead">Product questions rarely hide a secret correct solution. They create a sample of how you structure ambiguity, make choices, and communicate judgment.</p>
        <dl class="term-grid"><div><dt>Judgment</dt><dd>Choose with imperfect evidence and recognize the consequence.</dd></div><div><dt>Structure</dt><dd>Decompose the problem without turning the answer into a checklist.</dd></div><div><dt>Prioritization</dt><dd>Make criteria and opportunity cost explicit.</dd></div><div><dt>Communication</dt><dd>Make assumptions and recommendation easy to follow.</dd></div><div><dt>Ambiguity</dt><dd>Advance with controlled assumptions instead of freezing.</dd></div><div><dt>Ownership</dt><dd>Drive a decision and follow-up, not merely suggest analysis.</dd></div><div><dt>Business awareness</dt><dd>Connect value to revenue, cost, risk, and strategy.</dd></div><div><dt>Customer understanding</dt><dd>Separate roles, behavior, and the underlying problem.</dd></div><div><dt>Metrics</dt><dd>Select measures connected to causality and a decision.</dd></div><div><dt>Trade-offs</dt><dd>Name what is lost and why it is acceptable.</dd></div></dl>
        <p>An answer can disagree with the interviewer’s preference and remain strong if it frames the problem, states assumptions, considers alternatives, recommends, and measures. Reaching the expected solution by guessing demonstrates little seniority.</p>
        <p>Senior candidates calibrate depth. In ninety seconds, they offer a clear spine. When the interviewer probes, they expand evidence, segmentation, execution, and risk. They do not unload every known framework before identifying the central question.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Narrating an ideal process without a decision: “I would talk to users, analyze data, and align stakeholders.” Explain what each step seeks and how different findings change the recommendation.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Make reasoning observable. Structure is the container; judgment, causality, and trade-offs are the content.</aside>` },
      { id: 'capitulo-22', number: 22, title: 'How to answer without all the information', content: `
        <p class="lead">Incomplete information is part of the exercise. Saying only “I need more data” recognizes uncertainty but does not show that you can operate inside it.</p>
        <p>Ask high-value questions: which objective is threatened? Who is the target audience? Is the change recent? What is the magnitude and baseline? Is there an irreversible deadline? Then state assumptions for the rest.</p>
        <div class="language-box"><p><strong>“Based on the information available...”</strong> makes the recommendation proportionate.</p><p><strong>“I would first clarify...”</strong> identifies the question most capable of reversing the decision.</p><p><strong>“Assuming...”</strong> lets you advance without inventing a fact.</p><p><strong>“The decision would depend primarily on...”</strong> reveals the drivers.</p><p><strong>“I would use the following criteria...”</strong> makes judgment inspectable.</p></div>
        <p>For example: “Assuming the adoption decline began after the redesign and affects the core ICP, I would first verify exposure and errors by step. A clear regression would lead me to pause rollout. If exposure fell without functional failure, I would test discovery. My decision depends on severity, reversibility, and the effect on activation.”</p>
        <p>This combines epistemic humility with action. Ask no more than a few initial questions, state assumptions, give a conditional recommendation, and explain the signal that would make you change.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Creating so many conditions that no decision appears. Interviews assess the ability to recommend, not coverage of every possible reality.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> You do not need to know everything. You need to know which gap matters most, which assumption you adopted, and how evidence will change the action.</aside>` },
      { id: 'capitulo-23', number: 23, title: 'The ninety-second answer framework', content: `
        <p class="lead">A short answer must carry the problem, investigation, criteria, action, and learning. The framework creates a first layer the interviewer can explore.</p>
        <div class="diagram interview-framework" aria-label="Interview answer framework"><div class="node"><b>1</b> Frame the problem</div><div class="arrow">→</div><div class="node"><b>2</b> Investigate</div><div class="arrow">→</div><div class="node"><b>3</b> Decision criteria</div><div class="arrow">→</div><div class="node accent"><b>4</b> Recommend</div><div class="arrow">→</div><div class="node"><b>5</b> Measure & follow up</div></div>
        <ol><li><strong>Frame:</strong> restate the objective, audience, and tension.</li><li><strong>Investigate:</strong> choose two or three gaps capable of changing the decision.</li><li><strong>Criteria:</strong> explain how options will be compared.</li><li><strong>Recommend:</strong> take a position, even if conditional.</li><li><strong>Measure:</strong> define success, guardrails, and the next trigger.</li></ol>
        <h3>A ninety-second example</h3><blockquote>I would treat low adoption as a symptom, not proof of poor promotion. First I would define eligible users and inspect exposure, attempt, activation, and repetition by segment. I would interview adopters and non-adopters to separate awareness, usability, and value. Assuming users attempt and abandon, I would test the smallest change that removes that barrier. I would measure activation among exposed users, retained use, and Support tickets as a guardrail. I would scale only if the change creates recurring value, not merely clicks.</blockquote>
        <p>Practice with a timer, but do not memorize complete sentences. Memorize the causal order. For behavioral questions, replace the future recommendation with your past decision and learning.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Spending all ninety seconds on context and never reaching a recommendation. Limit the frame to two sentences.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> A senior answer is navigable: the listener knows where you are, why you moved, and what you would do next.</aside>` },
      { id: 'capitulo-24', number: 24, title: 'Weak, good, and excellent answers', content: `
        <p class="lead">The difference is not word count. Good answers name an analysis; excellent answers connect analysis to a decision, expose trade-offs, and anticipate follow-up.</p>
        ${interviewCasesHtml()}
        <aside class="callout takeaway"><strong>Takeaway.</strong> Use these cases as contrast practice. Read the prompt, answer aloud for ninety seconds, and only then compare your structure with the examples.</aside>` },
      { id: 'capitulo-25', number: 25, title: 'How to sound senior without empty jargon', content: `
        <p class="lead">Seniority appears in specificity, causality, and choice. Vocabulary helps, but it cannot replace a sentence that identifies the evidence sought and the decision it changes.</p>
        <div class="table-wrap"><table><thead><tr><th>Weak</th><th>Strong</th><th>What changed</th></tr></thead><tbody><tr><td>I would talk to customers.</td><td>I would combine qualitative interviews with product usage data to determine whether this is a recurring problem within our ICP.</td><td>Source, triangulation, pattern, and audience.</td></tr><tr><td>I would build a small version.</td><td>I would choose the lowest-cost test that reduces the most important uncertainty.</td><td>Small now refers to learning efficiency, not screen count.</td></tr><tr><td>I would prioritize the largest customer.</td><td>I would assess revenue at risk, strategic fit, broader segment demand, and opportunity cost before changing the roadmap.</td><td>Revenue receives weight without becoming the only criterion.</td></tr><tr><td>I would look at the data.</td><td>I would compare activation by acquisition channel and cohort to locate whether the decline begins before or after first value.</td><td>The data and decision gain a precise scope.</td></tr><tr><td>I would align stakeholders.</td><td>I would surface the conflicting objectives, clarify decision rights, and recommend an option with explicit consequences.</td><td>Alignment stops meaning “hold a meeting.”</td></tr></tbody></table></div>
        <h3>The pattern behind strong language</h3><p>Strong sentences contain a precise object, a reason, and a consequence. “Interview” becomes “reconstruct the latest workaround to test value risk.” “Metric” becomes “twenty-four-hour activation among eligible trials.” “Prioritize” becomes “accept the cost of delaying B to protect revenue and trust in A.”</p>
        <p>Use professional terms when they are shared names, then explain the logic. If asked what a guardrail is, answer without more jargon: “It is the measure that makes sure improving one thing does not create harm we consider unacceptable.”</p>
        <aside class="callout error"><strong>Common mistake.</strong> Using “data-driven” to avoid judgment. Data depends on definitions, instruments, and choices. Product Managers should be evidence-informed and accountable for decisions.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Sound senior by making relationships and consequences explicit. The goal is not to sound like a glossary; it is to make the decision difficult to misunderstand.</aside>
        <p class="reflection"><strong>Exercise:</strong> record three answers. Underline generic verbs such as analyze, align, and understand, then replace each with an object, criterion, and decision.</p>` }
    ]
  }
);
