'use strict';

const openingContent = `
  <header class="chapter-opening"><p class="chapter-kicker">A note to the reader</p><h2>This is not a book about memorizing frameworks</h2></header>
  <p class="lead">Frameworks compress thinking. They can organize a conversation, but they cannot make a decision for you. This book starts elsewhere: with the questions experienced professionals already ask when they must decide what is worth building.</p>
  <aside class="callout definition"><strong>How professional terms appear.</strong> The first time a Product term appears, it is underlined. Hover over it, focus it with the keyboard, or tap it to open a plain-English explanation, a concrete example, a common misuse, and a link to the glossary. You can learn the vocabulary without losing your place in the chapter.</aside>
  <p>You may have learned software by handling frustrated customers, negotiating scope with Engineering, rescuing an implementation, or protecting a small company's cash. In those situations, you probably asked whether the problem happened repeatedly, who was affected, what solving it would cost, and how anyone would know whether the change worked. That is already the raw material of Product Management.</p>
  <p>What is often missing is not product intelligence. It is an explicit system for ordering that reasoning and a shared vocabulary for communicating it. In an interview, saying “I would check whether similar customers experience this too” may be correct. Saying that you would validate the pattern within the <em>Ideal Customer Profile</em>, using qualitative and quantitative evidence, makes the same reasoning easier to evaluate and compare.</p>
  <aside class="callout takeaway"><strong>How to use this book.</strong> Read it in sequence once. After that, treat it as a field manual: return to the translation table when a term is missing, to the metrics chapters before an experiment, and to the interview section before a hiring process.</aside>
  <p>You do not need to replace your natural language with jargon. Strong Product Managers are not impressive because they use more specialized words. They are impressive because they make assumptions, choices, evidence, and consequences visible.</p>`;

const introductionContent = `
  <header class="chapter-opening"><p class="chapter-kicker">Introduction</p><h2>You probably already do Product Management</h2></header>
  <p class="lead">Product is a career with many side entrances. Developers arrive through systems thinking. Support and Customer Success arrive through proximity to pain. Project and Delivery Managers arrive through coordination. Founders arrive through responsibility for the whole business. None of these paths is incomplete; each creates a different combination of strengths and blind spots.</p>
  <p>Informal training has a cost. People who learned by doing often keep their criteria in their heads. They recognize an opportunity but do not separate observation from hypothesis. They make a trade-off but do not name the opportunity cost. They measure a release but mix adoption, activation, and retention. Shared context can hide this at work. It cannot hide it in interviews and assessments.</p>
  <h3>Why capable professionals get stuck</h3>
  <p>An interview question appears to ask for an answer: “Sales wants a feature to close a major contract. What do you do?” In reality, it observes a process. Can you separate the request from the underlying problem? Do you ask who buys and who uses? Can you consider revenue at risk without handing the strategy to the largest customer? Do you expose assumptions, recommend an action with incomplete information, and explain how you will learn?</p>
  <p>An experienced candidate may reach a sensible decision by intuition and still sound junior by jumping straight to the conclusion. The interviewer cannot evaluate invisible reasoning. Reciting RICE does not solve the problem either. A formula applied before the context is understood gives fragile assumptions a false appearance of precision.</p>
  <aside class="callout definition"><strong>Product thinking</strong> is the discipline of choosing relevant problems, reducing uncertainty, and connecting product changes to outcomes for customers and the business.</aside>
  <h3>An order that fits almost any decision</h3>
  <ol class="seven-list"><li>Is there a real problem?</li><li>Who experiences it?</li><li>Is it worth solving?</li><li>Do we have enough evidence?</li><li>What is the smallest investment that can create learning?</li><li>How will we measure success and risk?</li><li>What decision will the results trigger?</li></ol>
  <p>These questions form the spine of the book. They do not require a rigid sequence. During an incident, risk may force action before a complete investigation. In a strategic bet, the available evidence may remain weak by definition. Seniority is not ritual compliance. It is knowing what remains uncertain, why an exception is acceptable, and which consequence you are choosing to own.</p>
  <aside class="callout exercise"><strong>Before you continue.</strong> Choose a real product decision in which you participated. Write it in one sentence and mark which of the seven questions were answered explicitly. The gaps can become your path through the book.</aside>`;

const translations = [
  ['“Does this affect money, or is it merely annoying?”','Business impact','The effect on revenue, cost, risk, or a business objective.','When problems cause different kinds of pain.'],
  ['“How much could we lose if we do nothing?”','Revenue at risk','Existing or likely revenue exposed to churn, downgrade, or a lost deal.','Renewals, incidents, and major-account requests.'],
  ['“What are we hearing repeatedly?”','Voice of Customer (VoC)','A structured synthesis of signals from interviews, Support, reviews, and Sales.','When themes matter more than individual votes.'],
  ['“Does this happen to other people?”','Pattern validation','Checking whether a problem recurs across independent sources and customers.','Before generalizing one case.'],
  ['“Does it affect the customers we want to serve?”','ICP validation','Validating the problem inside the strategically desired customer profile.','When total volume may hide low strategic relevance.'],
  ['“What will we stop doing if we choose this?”','Opportunity cost','The value of the best alternative you give up.','Whenever capacity is reallocated.'],
  ['“What does waiting cost?”','Cost of delay','Value or risk that accumulates while an initiative waits.','Market windows, recurring loss, and operational risk.'],
  ['“We need to understand this before we build.”','Discovery','Work that reduces uncertainty about the problem, solution, and business.','Before and during investment decisions.'],
  ['“Now we need to make it real and reliable.”','Delivery','Turning a decision into usable, operable software.','Construction, launch, and stabilization.'],
  ['“How can we test this without betting everything?”','Experiment','A planned intervention designed to produce evidence about a hypothesis.','When uncertainty matters and an outcome can be observed.'],
  ['“We believe X will cause Y.”','Hypothesis','A falsifiable statement connecting an action, audience, mechanism, and outcome.','When the team needs to state what must be learned.'],
  ['“We are treating this as true.”','Assumption','An unproven belief on which the decision depends.','When mapping risk before investment.'],
  ['“How will we know it worked?”','Success metric','A measure connected to the intended outcome.','Before building or launching.'],
  ['“What must not get worse?”','Guardrail metric','A measure that protects the system from unacceptable collateral damage.','Local optimizations and rollouts.'],
  ['“Which signal should move first?”','Leading indicator','An early signal plausibly connected to a later result.','When the final result takes time.'],
  ['“Which result confirms value in the end?”','Lagging indicator','A later measure that confirms the accumulated outcome.','Retention, revenue, and churn.'],
  ['“How do we return safely?”','Rollback','Reversing a released change.','When operational or customer risk is material.'],
  ['“When do we stop?”','Kill criteria','A condition agreed in advance for ending a bet.','Expensive experiments or persistently weak results.'],
  ['“What exactly is included?”','Scope','The explicit boundary of cases, capabilities, and work.','To align expectations and control complexity.'],
  ['“What does this depend on?”','Dependency','An external condition required for progress or success.','Sequencing and risk assessment.'],
  ['“We are accepting one loss to gain something else.”','Trade-off','A conscious choice between benefits that cannot all be maximized.','Speed, quality, reach, and depth decisions.'],
  ['“Does this support the direction we chose?”','Strategic alignment','Consistency with the company’s positioning, goals, and chosen capabilities.','To resist opportunistic roadmaps.'],
  ['“Could the product fail or cause harm?”','Product risk','Uncertainty that can prevent value or create damage.','From discovery through post-launch monitoring.'],
  ['“Can people use it?”','Usability risk','The risk that people cannot understand or complete the experience.','New or complex workflows.'],
  ['“Do people need or want it?”','Value risk','The risk that the solution is not relevant enough to change behavior or justify payment.','Before full construction.'],
  ['“Can we build and operate it?”','Feasibility risk','Technical, performance, security, or operational uncertainty.','With Engineering and infrastructure.'],
  ['“Does it work for the business?”','Viability risk','Legal, financial, commercial, or operational uncertainty.','Monetization, contracts, and policy.'],
  ['“How many eligible people started using it?”','Adoption','Eligible users beginning to use a capability.','After launch, segmented by exposure.'],
  ['“How many reached first value?”','Activation','Completing the behavior that represents initial value.','Onboarding, trials, and PLG.'],
  ['“How deeply or frequently do they use it?”','Engagement','The frequency or depth of meaningful interaction.','When recurring use is connected to value.'],
  ['“Do they keep coming back?”','Retention','Continued use or continued presence after a defined period.','To evaluate durable value.'],
  ['“How many moved to the next stage?”','Conversion','The proportion completing a defined transition.','Signup, purchase, and activation funnels.'],
  ['“How many customers or dollars did we lose?”','Churn','The loss of customers or revenue during a period.','Customer-base health and growth quality.'],
  ['“Are existing customers spending more?”','Expansion revenue','Additional revenue from upgrades, seats, or usage.','SaaS growth inside existing accounts.'],
  ['“Did the base grow after losses?”','Net Revenue Retention (NRR)','Recurring revenue retained after expansion, contraction, and churn.','To understand the economics of the existing base.'],
  ['“What is annual recurring revenue?”','Annual Recurring Revenue (ARR)','Recurring revenue normalized to an annual value.','B2B SaaS and annual planning.'],
  ['“What is monthly recurring revenue?”','Monthly Recurring Revenue (MRR)','Recurring revenue normalized to a monthly value.','Monthly plans and shorter business cycles.'],
  ['“What does acquiring a customer cost?”','Customer Acquisition Cost (CAC)','Sales and marketing cost attributed to acquisition.','Evaluating growth efficiency.'],
  ['“How much economic value does a customer create?”','Customer Lifetime Value (LTV)','An estimate of customer value over the commercial relationship.','Comparing acquisition, retention, and margin.'],
  ['“When do we recover acquisition cost?”','Payback period','The time required for contribution margin to repay CAC.','Channel and growth decisions.'],
  ['“The product drives acquisition and value.”','Product-led growth (PLG)','A model in which the product experience drives growth.','Self-service, trial, and freemium products.'],
  ['“Sales drives the process.”','Sales-led','A model in which sellers qualify, demonstrate, negotiate, and close.','Complex contracts and high-value deals.'],
  ['“Usage tells Sales where to engage.”','Product-led sales','Using product signals to guide commercial intervention.','Accounts growing from self-service toward enterprise.'],
  ['“Which direction and sequence will we communicate?”','Roadmap','A narrative of problems, outcomes, and bets over time.','Aligning choices and dependencies.'],
  ['“What work could we still choose?”','Backlog','A prioritizable inventory of opportunities, tasks, and debt.','Operational management, not strategy.'],
  ['“What change do we want to produce?”','Outcome','An observable change in behavior or results.','Defining a product objective.'],
  ['“What did we ship?”','Output','An artifact such as a feature, screen, or API.','Tracking execution without confusing it with impact.'],
  ['“Which bet groups this work?”','Initiative','A coherent set of efforts oriented toward an objective.','Roadmaps and planning.'],
  ['“What is the large delivery block?”','Epic','An operational grouping of related stories or tasks.','Delivery organization, not product justification.'],
  ['“What is the smallest version that delivers real value?”','Minimum viable product (MVP)','The smallest usable product that tests value in real use.','When learning requires a functional experience.'],
  ['“Can we simulate the experience?”','Prototype','A representation used to test understanding, flow, or desirability.','Before production code.'],
  ['“Does the critical technology work?”','Proof of concept (PoC)','A limited implementation used to test technical feasibility.','When technical uncertainty dominates.'],
  ['“Can we release it to a controlled group?”','Beta','A real but restricted release used for learning and stabilization.','Before broad availability.'],
  ['“Who will learn with us?”','Design partner','A customer who participates actively in discovery and validation.','Early B2B products and complex problems.']
];

function translationTable() {
  return `<div class="table-wrap"><table><thead><tr><th>What you may already think</th><th>Professional term</th><th>What it means</th><th>When it helps</th></tr></thead><tbody>${translations.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}

const BOOK_PARTS = [
  {
    id: 'parte-1', title: 'Part I — Recognizing product reasoning', chapters: [
      { id: 'capitulo-1', number: 1, title: 'The real work of a Product Manager', content: `
        <p class="lead">The central job of Product is not producing features. It is improving the quality of decisions about where to invest limited capacity while customers, technology, and the market keep changing.</p>
        <p>Tickets, rituals, and roadmaps are coordination mechanisms. A PM can maintain a perfect backlog and still fail if the team is solving an irrelevant problem. The reverse is also true: a PM can create value without owning every ritual by helping the group choose better, learn earlier, and connect work to results.</p>
        <h3>Decision-making under uncertainty</h3><p>Almost every important decision occurs before complete information exists. We do not know exactly how many users experience the pain, whether they will change behavior, what the solution will cost to operate, or how competitors will respond. The goal is not to remove all uncertainty. It is to identify which uncertainty could reverse the decision and reduce it at a proportionate cost.</p>
        <p>Imagine a time-management SaaS in which ten customers request custom reports. The analysis should not begin with an estimate. It should begin by separating possible problems: managers cannot demonstrate profitability, Finance cannot reconcile billing, or each account wants to reproduce a historical spreadsheet. One apparent feature request hides different jobs and therefore different solutions.</p>
        <h3>Scarce resources and trade-offs</h3><p>Engineering capacity is the most visible scarcity, but it is not the only one. User attention, tolerable complexity, Support capacity, and stakeholder trust are finite too. Every addition occupies mental space and creates future maintenance. “It is cheap” can never end the analysis.</p>
        <div class="comparison"><div><h4>Output</h4><p>A dashboard shipped; an integration released; twelve tickets completed.</p></div><div><h4>Outcome</h4><p>Managers identify unprofitable projects; new users reach first value sooner.</p></div></div>
        <p>Outputs are immediate and mostly controllable. Outcomes depend on behavior and context. Mature teams monitor both: they need to deliver well, but they judge the bet by the change it produces.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Treating alignment as approval for a solution that has already been selected. Real alignment makes the problem, evidence, assumptions, alternatives, and accepted losses understandable.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> A PM connects customer, product, and business to make choices explicit. Seniority appears less in the number of answers and more in the ability to separate fact, hypothesis, risk, and trade-off.</aside>
        <p class="reflection"><strong>Reflection:</strong> which release consumed meaningful capacity last quarter without a clearly observed outcome?</p>` },
      { id: 'capitulo-2', number: 2, title: 'The seven questions behind every decision', content: `
        <p class="lead">The seven questions operate as a decision tree. They stop a conversation from jumping directly from a complaint to the roadmap, and they force the team to state what it knows.</p>
        <div class="diagram seven-tree" aria-label="Seven-question decision tree"><div class="node root">Product decision</div><div class="arrow">↓</div>${['1. Real problem?','2. Who experiences it?','3. Worth solving?','4. Enough evidence?','5. Smallest test?','6. Success and risk?','7. What decision follows?'].map(x => `<div class="node">${x}</div>`).join('<div class="arrow">↓</div>')}</div>
        <h3>1. Is there a real problem?</h3><p>A problem is an observable difficulty, not the absence of a feature. “We do not export PDFs” describes the product. “Consultants spend two hours rebuilding reports for clients” describes a cost. In B2B SaaS, look for behavior, frequency, and consequence. <strong>Mistake:</strong> treating verbal intensity as frequency. <strong>Interview prompt:</strong> “How would you validate this request?”</p>
        <h3>2. Who experiences it?</h3><p>Name the user, buyer, account, segment, and context. Advanced permissions may help enterprise admins while damaging self-service simplicity. <strong>Mistake:</strong> using “the customer” as a homogeneous group. <strong>Interview prompt:</strong> “For whom would you build first?”</p>
        <h3>3. Is it worth solving?</h3><p>Combine severity and reach with economic impact, strategic fit, and opportunity cost. A real problem may still not belong in your product. <strong>Mistake:</strong> equating one account's revenue with the attractiveness of the problem. <strong>Interview prompt:</strong> “How would you choose between two opportunities?”</p>
        <h3>4. Do we have enough evidence?</h3><p>Enough evidence depends on reversibility. Changing interface copy requires less certainty than rebuilding an authorization architecture. Triangulate what people say, what they do, and what consequences occur. <strong>Mistake:</strong> demanding certainty or acting on one anecdote. <strong>Interview prompt:</strong> “What would you investigate first?”</p>
        <h3>5. What is the smallest investment that can create learning?</h3><p>Choose the method for the uncertainty. Use a prototype for usability, a concierge test for value, a proof of concept for feasibility, and a limited rollout for operational risk. <strong>Mistake:</strong> calling an incomplete feature an MVP. <strong>Interview prompt:</strong> “How would you reduce the risk of this bet?”</p>
        <h3>6. How will we measure success and risk?</h3><p>Define a primary metric, early signals, and guardrails. For onboarding, activation may be primary, completion of initial setup may lead, and Support tickets may guard against hidden confusion. <strong>Mistake:</strong> choosing only what is easy to instrument. <strong>Interview prompt:</strong> “How would you measure success?”</p>
        <h3>7. What decision will the results trigger?</h3><p>Before the test, agree on the conditions for iterating, scaling, or rolling back. Without a rule, almost any result can be rationalized. <strong>Mistake:</strong> collecting data without a decision commitment. <strong>Interview prompt:</strong> “What would you do if the primary metric improved but Support got worse?”</p>
        <aside class="callout example"><strong>Integrated example.</strong> An e-commerce operations product receives requests for bulk editing. The team identifies stores with large catalogs, confirms hours lost each week, estimates retention impact, tests a clickable workflow, measures completed tasks and errors, releases to ten stores, and expands only if time falls without a material increase in incorrect changes.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> The questions are not a bureaucratic checklist. They protect the team from falling in love with the first available explanation.</aside>` },
      { id: 'capitulo-3', number: 3, title: 'The mistake of starting with the solution', content: `
        <p class="lead">Feature requests are valuable data about context and expectation. They are not finished specifications. Customers understand their own reality; the product team must discover which problem generalizes and which response preserves product coherence.</p>
        <div class="diagram request-flow" aria-label="Feature request versus underlying problem"><div class="node">“Send a daily export by email”</div><div class="arrow">→</div><div class="node accent">Why? In which situation?</div><div class="arrow">→</div><div class="node">A manager needs to see variance before a weekly review</div><div class="arrow">→</div><div class="node">Alerts, digest, or dashboard</div></div>
        <p>Investigate the job behind the request. When did the person last try to do this? What triggered the need? How is it handled today? What time, money, or risk does the workaround create? Who consumes the result? What happens if nothing changes?</p>
        <h3>“The customer asked” is not enough</h3><p>A request may represent a preference, a purchasing condition, an onboarding limitation, or familiarity with another tool. Sales hears prospects at the moment of objection. Support hears users when something fails. Usage data records the behavior of people who managed to get in. Every source has a sampling bias. Product synthesizes them rather than choosing a favorite source.</p>
        <h3>Handling enterprise requests</h3><p>Separate revenue at risk, recurrence in the ICP, strategic fit, generalizability, and total cost. Work for one customer can make sense when it protects material revenue, supports a strategic capability, or funds learning that benefits a broader segment. Make the exception explicit, bound the maintenance burden, and define a path toward a reusable capability or removal.</p>
        <p>A strong response might be: “We will not treat the requested format as a requirement yet. This week, we will map the compliance workflow with this account and three similar ones; in parallel, Engineering will assess whether our export layer can support a configurable approach. Then we will choose between a design partnership, a general integration, or a temporary service.” That is not indecision. It reduces the uncertainty most likely to change the investment.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Replacing the requested feature with the PM's preferred feature before understanding the problem. Solution bias is still solution bias when it comes from Product.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Respect the signal, investigate the progress the customer needs, and select a solution only after the decision criteria are visible.</aside>
        <p class="reflection"><strong>Exercise:</strong> take three backlog items written as features and rewrite each as a problem, audience, and consequence.</p>` },
      { id: 'capitulo-4', number: 4, title: 'Who actually has the problem?', content: `
        <p class="lead">In B2B products, “the customer” is rarely one person. The people who sign, pay, administer, and use the product may have opposing incentives. Good decisions require naming those roles.</p>
        <dl class="term-grid"><div><dt>User / End user</dt><dd>The person performing work in the product. They may receive value without choosing the purchase.</dd></div><div><dt>Buyer</dt><dd>The person running the buying process and evaluating price, risk, and vendor terms.</dd></div><div><dt>Economic buyer</dt><dd>The person with final authority over the budget.</dd></div><div><dt>Customer</dt><dd>The account or commercial relationship. Use it carefully when individual roles matter.</dd></div><div><dt>Stakeholder</dt><dd>Anyone who influences or is affected, including Legal, Security, Finance, Support, and partners.</dd></div><div><dt>Champion</dt><dd>An internal advocate who mobilizes adoption and navigates the organization.</dd></div><div><dt>Detractor</dt><dd>A person whose incentives, risk, or experience creates active resistance.</dd></div><div><dt>Persona</dt><dd>A behavioral archetype describing responsibilities, context, and constraints.</dd></div><div><dt>Segment</dt><dd>A group defined by attributes useful for analysis or action.</dd></div><div><dt>ICP</dt><dd>The type of company with the strongest combination of need, value, and strategic fit.</dd></div></dl>
        <p>Imagine a time-tracking product. Consultants record hours; managers demand consistency; Finance invoices; a COO buys; Security approves; and a team lead acts as champion. Onboarding that pleases the COO but requires twenty fields for every record may help the sale and destroy adoption.</p>
        <h3>Map value and power</h3><p>For each decision, identify who experiences the pain, who receives the value, who must change behavior, who can block, who pays, and who carries risk. In PLG products, one person may hold several roles initially and then lose them as the account grows. That separation is an important signal for product-led sales.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Creating decorative personas with age, hobbies, and a stock photo. A persona is useful only when it explains behavior relevant to the decision: task frequency, autonomy, skill, motivation, and constraints.</aside>
        <aside class="callout example"><strong>Example.</strong> In an app for online stores, the owner may be both buyer and user. In an agency, the owner buys, a specialist uses, and end clients become stakeholders. The same approval flow can create very different value and friction.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Segmentation is not labeling. It prevents misleading averages and makes the choice of whom the product should serve explicit.</aside>` }
    ]
  },
  {
    id: 'parte-2', title: 'Part II — The translation dictionary', chapters: [
      { id: 'capitulo-5', number: 5, title: 'What you think versus what Product calls it', content: `
        <p class="lead">Professional vocabulary is useful when it increases precision. The table does not ask you to replace plain speech with jargon. It helps you recognize concepts, research them, and participate in decisions using shared language.</p>
        ${translationTable()}
        <aside class="callout error"><strong>Common mistake.</strong> Using a term as decoration. Saying “opportunity cost” without naming the alternative being abandoned adds no information.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Translate both ways. Begin in ordinary language to understand the problem; use the professional term to connect it to an established body of reasoning.</aside>` },
      { id: 'capitulo-6', number: 6, title: 'Metrics that look similar but are not', content: `
        <p class="lead">Metrics tell different parts of a story. The frequent error is not calculating a number incorrectly. It is using a true number to answer the wrong question.</p>
        <h3>Adoption, activation, engagement, and retention</h3><p><strong>Adoption</strong> asks whether eligible people started using a capability. <strong>Activation</strong> asks whether they reached an early value-producing behavior. <strong>Engagement</strong> asks how frequently or deeply meaningful use occurs. <strong>Retention</strong> asks whether the behavior or relationship continues over time. A person can adopt without activating, activate once without retaining, or engage heavily with a peripheral capability.</p>
        <h3>Conversion, revenue, and satisfaction</h3><p>Conversion requires a defined transition and denominator: visitor to signup, trial to paid, activated user to invited team. Revenue combines price, volume, expansion, contraction, and timing. Satisfaction captures perception, which may predict loyalty or simply reflect a recent interaction. NPS is a standardized recommendation question; it does not replace behavioral investigation.</p>
        <h3>Support volume and time to value</h3><p>Support volume can rise because the experience deteriorated, the customer base grew, or a previously ignored feature became popular. Normalize by active users, theme, and severity. <em>Time to value</em> measures how long the target user takes to reach a meaningful result, not merely to finish a tutorial.</p>
        <div class="scenario-grid"><article><h4>Activation rises; retention does not</h4><p>Onboarding removed friction, but recurring value is weak or the activation event is poorly defined.</p></article><article><h4>Conversion rises; Support and churn worsen</h4><p>The promise or discount may attract low-fit customers, or hide complexity until after purchase.</p></article><article><h4>Revenue grows; product quality declines</h4><p>Pricing and annual contracts can mask experience debt. Examine behavioral cohorts and renewal quality.</p></article></div>
        <aside class="callout error"><strong>Common mistake.</strong> Choosing a metric because a dashboard already contains it. Begin with the decision and causal story, then choose the measure.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Every metric needs a population, event, window, and interpretation. Without those four elements, a number invites argument instead of guiding action.</aside>
        <p class="reflection"><strong>Exercise:</strong> for a recent feature, define adoption, activation, and retention separately. If you cannot, there is a gap in definition or instrumentation.</p>` },
      { id: 'capitulo-7', number: 7, title: 'Leading, lagging, and guardrail metrics', content: `
        <p class="lead">A metric can move too early to prove value or too late to guide the next week. A useful system combines anticipation, confirmation, and protection.</p>
        <div class="diagram metric-flow" aria-label="Leading, lagging, and guardrail metrics"><div class="node"><small>Objective</small>Increase retention</div><div class="arrow">→</div><div class="node accent"><small>Leading</small>More users complete the first workflow</div><div class="arrow">→</div><div class="node"><small>Lagging</small>30-day retention</div><div class="guard"><small>Guardrail</small>Support tickets and task time do not worsen</div></div>
        <p>A <strong>leading indicator</strong> appears early and has a plausible relationship with the outcome. It is not proof. If users who complete a workflow retain more, increasing completion seems promising, but the relationship may simply reflect already-motivated users. A <strong>lagging indicator</strong> confirms the result after the necessary window. A <strong>guardrail metric</strong> states the price the team refuses to pay.</p>
        <h3>A practical selection method</h3><ol><li>State the outcome as behavior or a business result.</li><li>Draw the causal chain between the intervention and the outcome.</li><li>Select the earliest meaningful behavior as the leading indicator.</li><li>Define the final measure and its window as the lagging indicator.</li><li>Identify who or what could be harmed and create guardrails.</li></ol>
        <p>Suppose a shorter signup flow increases completed registrations. Activation may still fall because essential configuration was postponed without guidance. Registration completion leads, recurring successful workflows lag, and setup errors guard against a false win.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Calling any fast-moving metric “leading.” The indicator needs a defensible mechanism connecting it to the desired result.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Leading guides early, lagging confirms later, and guardrails prevent a local victory from damaging the wider system.</aside>` },
      { id: 'capitulo-8', number: 8, title: 'ICP, persona, and segment', content: `
        <p class="lead">ICP answers “what kind of company should we serve especially well?” Persona answers “which person, in which context, needs to act?” Segment answers “which group do we want to compare or treat differently?”</p>
        <div class="diagram icp-persona" aria-label="ICP versus persona"><div class="node wide"><small>ICP · company</small>Remote digital agencies, 20–100 people, hourly billing, integrable SaaS tools</div><div class="connector">contains</div><div class="node"><small>Persona · person</small>Operations manager responsible for utilization and margin</div><div class="connector">analyzed as</div><div class="node"><small>Segment</small>Accounts activated through a project-tool integration</div></div>
        <p>An ICP combines attributes that predict need, ability to obtain value, willingness to pay, cost to serve, and strategic fit. “SMB” is rarely enough. Two fifty-person companies can have completely different workflows, urgency, and buying processes.</p>
        <p>A persona should contain responsibilities, triggers, behavior, constraints, and success criteria. “A 35-year-old manager interested in productivity” is useless. “A delivery manager who closes project profitability every Friday, depends on time entries from forty consultants, and cannot stop their work” can guide design.</p>
        <h3>Four contexts</h3><ul><li><strong>Time-management SaaS:</strong> the ICP may be an agency selling hours; personas include contributor, manager, and Finance.</li><li><strong>B2B enterprise:</strong> the ICP includes security maturity and process complexity; buyer and end user separate.</li><li><strong>E-commerce app:</strong> segment by order volume, catalog size, and in-house versus agency operation.</li><li><strong>Remote teams:</strong> distributed time zones, asynchronous work, and autonomy may explain more than country.</li></ul>
        <p>Segments can be firmographic, behavioral, need-based, value-based, or lifecycle-based. Create them for a decision: compare retention, adapt onboarding, or select a rollout group. A segment that changes neither analysis nor action is merely a label.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Defining the ICP as a description of whoever already buys. The current base contains historical accidents; an ICP is a choice about where fit can become stronger and sustainable.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> ICP guides strategy, persona guides experience, and segment guides analysis or action. They connect, but they are not interchangeable.</aside>` }
    ]
  },
  {
    id: 'parte-3', title: 'Part III — Discovery and evidence', chapters: [
      { id: 'capitulo-9', number: 9, title: 'How to know whether the problem is real', content: `
        <p class="lead">Real problems leave different kinds of traces. People describe them, change behavior, build workarounds, and experience consequences. Strong discovery combines those traces instead of searching for one perfect source.</p>
        <h3>Quantitative and qualitative evidence</h3><p>Quantitative evidence helps answer how many, where, and for whom: event frequency, funnel abandonment, failed searches, cohorts, churn, and revenue. Qualitative evidence helps answer why and how: interviews, Support tickets, Sales calls, advisory boards, and observation. Usage data may show that 42% abandon a step; an interview may reveal that the step requires information the user does not yet have. The interview cannot prove prevalence, and the funnel cannot explain motivation.</p>
        <h3>Sources and their biases</h3><ul><li><strong>Support tickets:</strong> concrete language and severity, limited to people who asked for help.</li><li><strong>Sales objections:</strong> purchase barriers, biased toward prospects and negotiation.</li><li><strong>Usage data and funnels:</strong> behavior at scale, limited to what was instrumented.</li><li><strong>Search logs:</strong> spontaneous intent, but ambiguous words.</li><li><strong>Win/loss analysis:</strong> commercial comparison affected by price, process, and memory.</li><li><strong>Churn reasons:</strong> a strong consequence, but often late and rationalized.</li><li><strong>Advisory boards:</strong> depth and partnership, with atypical participants.</li><li><strong>Market research:</strong> context and alternatives, distant from specific product behavior.</li></ul>
        <h3>Triangulation</h3><p>Build an evidence matrix with the hypothesis in rows and sources in columns. Look for convergence and contradiction. Three independent accounts describing the same workaround, usage data showing the relevant abandonment, and churn notes naming the consequence form a stronger pattern than ten repeated tickets from one incident.</p>
        <p>Enough evidence depends on cost and reversibility. Interface copy can move forward after a handful of sessions and monitoring. Migrating every account to a new permission model requires broader data, feasibility work, rollout controls, and a rollback plan.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Searching only for evidence that confirms the preferred solution. Write down in advance what would increase and what would reduce confidence.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> A validated problem is not universal certainty. It is proportionate evidence, for a defined audience, strong enough to justify the next reversible investment.</aside>
        <p class="reflection"><strong>Exercise:</strong> choose one opportunity and create three columns: what people say, what they do, and which consequence appears.</p>` },
      { id: 'capitulo-10', number: 10, title: 'What Sales says and what customers do', content: `
        <p class="lead">Sales and Product observe different moments in the customer journey. Their conflict is not a character flaw. It is a problem of sampling, incentives, and time horizon.</p>
        <p>Sales is close to prospect urgency, quarterly targets, and competitive alternatives. Existing users reveal adoption, quality, and recurring value. Enterprise accounts expose governance requirements and material revenue. Self-service users reveal scale and clarity. Strategic segments represent where the company has chosen to compete. No group owns the complete truth.</p>
        <h3>Classify the signal</h3><dl class="term-grid"><div><dt>Sales objection</dt><dd>Something mentioned to delay or negotiate. Verify whether it changes the purchase decision.</dd></div><div><dt>Real need</dt><dd>A barrier connected to an observable workflow and consequence.</dd></div><div><dt>Parity feature</dt><dd>A capability expected because alternatives have it. It may be a requirement or merely a comparison.</dd></div><div><dt>Strategic differentiator</dt><dd>A capability that reinforces the chosen position and is difficult to substitute.</dd></div><div><dt>Isolated request</dt><dd>A signal without enough recurrence or fit to generalize.</dd></div><div><dt>Recurring problem</dt><dd>A similar pattern across relevant sources and accounts.</dd></div></dl>
        <h3>A conversation framework</h3><ol><li><strong>Capture:</strong> account, segment, stage, potential value, and original wording.</li><li><strong>Contextualize:</strong> which job, consequence, and alternative sit behind it?</li><li><strong>Compare:</strong> how many independent occurrences exist in the ICP? What do usage and Support show?</li><li><strong>Size:</strong> revenue at risk, frequency, severity, and cost to serve.</li><li><strong>Decide:</strong> discovery, workaround, design partner, build, partnership, or not now.</li><li><strong>Close the loop:</strong> explain the criteria and return learning to Sales.</li></ol>
        <p>Suppose three prospects request SSO. In 500-person accounts, Security blocks trials without it; approved competitors provide it; and the architecture can support a general identity provider. This is a recurring ICP requirement, not a preference. Another prospect wants a report in its parent company's internal layout. The job may be solved by configurable export, but the precise format remains an isolated request.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Responding to Sales only with roadmap position. That turns collaboration into date negotiation and prevents better signal quality.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Do not count votes or choose a side. Build a system that converts commercial and behavioral signals into comparable evidence.</aside>` },
      { id: 'capitulo-11', number: 11, title: 'Interviews that reveal problems', content: `
        <p class="lead">A discovery interview is not a request for approval. Its purpose is to reconstruct behavior, context, decisions, and cost with enough detail to guide a bet.</p>
        <div class="table-wrap"><table><thead><tr><th>Weak question</th><th>Better question</th><th>Why it is better</th></tr></thead><tbody><tr><td>Would you use automatic alerts?</td><td>Tell me about the last time a project exceeded its budget. How did you notice?</td><td>Replaces hypothetical intent with past behavior.</td></tr><tr><td>Is this a big problem?</td><td>What happened next? Who became involved, and how long did it take?</td><td>Finds consequences instead of subjective scale.</td></tr><tr><td>Which feature do you want?</td><td>How do you handle this today? Show me the latest example.</td><td>Reveals workarounds and real criteria.</td></tr><tr><td>Would you pay for this?</td><td>Who approves this purchase, and what would need to be true?</td><td>Investigates process and economic trade-offs.</td></tr></tbody></table></div>
        <h3>Reconstruct the episode</h3><p>Begin broadly, then deepen: “When did this last happen?”, “What triggered it?”, “What did you do next?”, “Where did you stop?”, “Who helped?”, “Which tool did you open?”, “What would happen if it remained unresolved?” When appropriate, ask for real artifacts such as a spreadsheet, ticket, message, calendar, or report without sensitive data.</p>
        <p>Workarounds are evidence of effort, not proof of a market. A spreadsheet maintained every week by five managers in the ICP suggests frequency and value. A macro built once by a power user may be peripheral behavior. Look at cost, repetition, substitutes, and authority to change.</p>
        <h3>Avoid leading</h3><p>Do not hide your hypothesis inside the question. Instead of “Permissions are confusing, right?”, ask the person to configure a recent case and narrate expectations. Allow silence. At the end, test your understanding: “I heard that the largest cost occurs during the monthly review, not during setup. Is that accurate?”</p>
        <p>An interview should not end as a transcript. Record observed facts, a short quote, your interpretation, the next question, and the implication. Compare themes by session and segment. One memorable story must not outweigh four contradictory accounts.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Asking “Would you use it?” and converting positive answers into demand. People are generous in conversation and conservative when behavior, money, or coworkers must change.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Concrete past behavior predicts more than an imagined future. Look for episodes, artifacts, workarounds, and consequences.</aside>
        <p class="reflection"><strong>Exercise:</strong> rewrite five validation questions for your next interview as requests for past behavior.</p>` },
      { id: 'capitulo-12', number: 12, title: 'Hypotheses, assumptions, and risks', content: `
        <p class="lead">Opinions become manageable when they are written as assumptions and connected to risks. The purpose is not bureaucracy. It is to find the fragile belief supporting an expensive bet.</p>
        <p><strong>Assumption:</strong> “Admins have permission to invite the entire team.” <strong>Hypothesis:</strong> “If accounts with more than thirty users can import members from CSV, seven-day setup completion will increase because manual invitations are the primary barrier.” The hypothesis contains an audience, intervention, behavior, and mechanism. Evidence can contradict it.</p>
        <div class="risk-grid"><article><h3>Value risk</h3><p>Does the problem matter? Does the solution create enough value to justify change or payment?</p><p><strong>Tests:</strong> interview, concierge, fake door, commitment.</p></article><article><h3>Usability risk</h3><p>Can people understand and complete the task?</p><p><strong>Tests:</strong> prototype and usability session.</p></article><article><h3>Feasibility risk</h3><p>Can the team build, scale, secure, and operate it?</p><p><strong>Tests:</strong> technical spike and proof of concept.</p></article><article><h3>Viability risk</h3><p>Does it work for the business model, Legal, Sales, Support, and policy?</p><p><strong>Tests:</strong> operational review, pricing smoke test, and contract analysis.</p></article></div>
        <h3>From map to test</h3><ol><li>Write the decision you want to make.</li><li>List what must be true for it to work.</li><li>Classify each belief by risk type.</li><li>Estimate uncertainty and damage if wrong.</li><li>Test the most dangerous combination first.</li></ol>
        <p>Consider an AI-generated export summary. Value: will managers trust it? Usability: can they review and correct it? Feasibility: do cost and latency fit? Viability: may customer data be processed this way? A polished interface reduces little risk when compliance could kill the idea.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Testing what is easy instead of what can kill the idea. A beautiful prototype does not reduce the technical risk of processing millions of records.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> A hypothesis gives a belief testable form; the risk map decides where to learn. Strong tests maximize uncertainty reduction per unit of investment.</aside>` }
    ]
  },
  {
    id: 'parte-4', title: 'Part IV — Prioritization and strategy', chapters: [
      { id: 'capitulo-13', number: 13, title: 'The highest-paying customer should not always come first', content: `
        <p class="lead">Revenue matters. The mistake is treating it as the only criterion and ignoring concentration, direction, generalizability, and total cost. A large customer can fund a strategic capability or turn the product into a collection of exceptions.</p>
        <h3>When to prioritize the large customer</h3><p>Prioritize when material revenue is genuinely at risk, the problem recurs inside the ICP, the solution strengthens a capability other accounts will use, the commitment supports strategy, and maintenance remains sustainable. A general SSO capability that unlocks a renewal and a wider enterprise motion can meet those conditions.</p>
        <h3>When not to prioritize</h3><p>Do not prioritize automatically when the request reproduces a unique internal process, creates a fork, requires permanent manual operations, displaces a more strategic bet, or relies on a vague churn threat. A custom report may close a contract while increasing dependence on an account whose workflow will never become product.</p>
        <h3>Small segments and small initiatives</h3><p>A small segment can deserve investment when it is a beachhead, has intense pain, low acquisition cost, strong expansion, or teaches a central capability. Similarly, a small password-recovery improvement may affect revenue more than a large analytics page if it removes a frequent activation barrier.</p>
        <p>Assess strategic fit, revenue at risk, concentration risk, adjacent demand, the opportunity being abandoned, and debt created. State the horizon. Saving this quarter's revenue can be rational without lasting fit when the exception is deliberate and bounded.</p>
        <aside class="callout example"><strong>Case.</strong> One customer represents 18% of ARR and requests multilevel approval. Three prospects in the ICP face the same barrier. The current architecture does not support rules. A senior decision may be discovery and a design partnership now, rather than a delivery-date promise. This protects the relationship while validating generalizability and feasibility.</aside>
        <aside class="callout error"><strong>Common mistake.</strong> Using “strategy” to reject revenue without quantifying the consequence. Strategy is a choice with accepted losses, not protection from pressure.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Customer size changes the weight of a request; it does not end the analysis. Decide through the combination of economics, fit, risk, and future capacity.</aside>` },
      { id: 'capitulo-14', number: 14, title: 'How to prioritize when everything is urgent', content: `
        <p class="lead">When everything is urgent, shared criteria are usually missing or the same capacity has been promised more than once. Prioritization begins by making problems comparable, not by assigning points to poorly defined solutions.</p>
        <div class="diagram priority-diagram" aria-label="Prioritization by impact, confidence, and effort"><div class="formula"><span>User impact</span><b>×</b><span>Business impact</span><b>×</b><span>Alignment</span><b>×</b><span>Confidence</span><b>÷</b><span>Effort + risk</span></div><p>Cost of delay, dependencies, and reversibility adjust the sequence.</p></div>
        <h3>A practical framework</h3><ul><li><strong>User impact:</strong> reach, frequency, and severity within the target audience.</li><li><strong>Business impact:</strong> revenue, cost, risk, and advantage.</li><li><strong>Strategic alignment:</strong> contribution to the chosen position and objectives.</li><li><strong>Confidence:</strong> quality of evidence, not the proposer's conviction.</li><li><strong>Effort:</strong> discovery, construction, rollout, operation, and maintenance.</li><li><strong>Cost of delay:</strong> value lost per unit of time.</li><li><strong>Risk:</strong> value, usability, feasibility, and viability.</li><li><strong>Dependencies:</strong> imposed order or an opportunity to unlock other work.</li><li><strong>Reversibility:</strong> cost of correcting or returning.</li></ul>
        <p>Use a short scale with anchored descriptions. Instead of “impact 9,” write “affects more than 40% of the ICP every week and blocks a core task.” First screen for strategy and obligation; then compare the surviving opportunities. Separate incidents and unavoidable commitments from discretionary bets.</p>
        <h3>The limits of scoring</h3><p>RICE and similar models make assumptions visible, but multiplication creates an appearance of objectivity. Estimates are not independent, effort is uncertain, and an emerging strategic opportunity may have low confidence precisely because it is new. Use a score as a discussion prompt and test sensitivity: does the ranking change if effort doubles or reach falls?</p>
        <p>For three urgent initiatives, state the objective, show real capacity, and present a sequence with consequences: “If we protect the regulatory migration and checkout reliability, the dashboard moves by two weeks. If we preserve the dashboard date, we accept regulatory or conversion risk.” Choosing requires making the loss explicit.</p>
        <aside class="callout error"><strong>Common mistake.</strong> Scoring items after leaders have already decided and using the spreadsheet to legitimize the outcome. That destroys trust in the method.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Frameworks support judgment; they do not outsource it. Strong prioritization produces an explainable decision and a clear list of what will not be done.</aside>` },
      { id: 'capitulo-15', number: 15, title: 'A roadmap is not a list of promises', content: `
        <p class="lead">A roadmap communicates direction, sequence, and confidence. When it becomes a list of features with equally firm dates, it hides uncertainty and turns learning into delay.</p>
        <p>An outcome-oriented roadmap organizes problems and results: reduce time to first value, increase collaboration in team accounts, decrease billing failures. Initiatives are bets intended to move those results. Dates appear when a real commitment exists, such as a regulatory obligation, a deliberate contract, or a go-to-market dependency.</p>
        <h3>Three commitment levels</h3><ol><li><strong>Committed:</strong> scope and date have high confidence and little room for change.</li><li><strong>Planned:</strong> problem and window are prioritized, while solution or reach remains adjustable.</li><li><strong>Exploring:</strong> the opportunity is in discovery with no delivery promise.</li></ol>
        <p>Capacity constraints must be visible. Reserve space for reliability, debt, discovery, and predictable interruption. When capacity falls, do not spread silent delay across everything. Reduce scope while protecting the outcome, change sequencing, or renegotiate the commitment.</p>
        <h3>Communicating reprioritization</h3><p>Explain what changed, which evidence appeared, what objective gains protection, what moves, and when the decision will be reviewed. “We changed our mind” sounds unstable. “Churn among manually activated accounts doubled and now threatens the annual objective; we will pause analytics for two weeks to repair activation and measure recovery” demonstrates control.</p>
        <aside class="callout example"><strong>Lean roadmap.</strong> Now: reduce failures in the first workflow. Next: increase collaboration among activated teams. Later: explore enterprise governance. For each horizon, show the outcome, audience, evidence, indicator, and confidence.</aside>
        <aside class="callout error"><strong>Common mistake.</strong> Treating every stakeholder conversation as a commitment. Capture the interest and need; promise only when authority, capacity, and risk are aligned.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> A useful roadmap enables coordination without pretending certainty. It shows what matters, why it comes first, and how firm each element is.</aside>` },
      { id: 'capitulo-16', number: 16, title: 'The invisible cost of cheap features', content: `
        <p class="lead">“Engineering can do it in two days” describes only a fraction of the cost. Every feature enters a technical, operational, and cognitive system that continues to exist after the merge.</p>
        <p>Total cost includes maintenance, Support, documentation, recurring QA, analytics, compatibility, localization, accessibility, security, Sales enablement, and future migrations. It also includes <strong>UX complexity</strong>: more options make every decision slower. And it includes <strong>cognitive load</strong>: users must understand the mental model, not merely find the button.</p>
        <p>A preference such as “hide weekends” appears cheap. It must still behave consistently in calendars, reports, exports, mobile, time zones, and templates. Support must explain exceptions; data must distinguish hidden from missing. The initial code may cost two days and the product may pay for years.</p>
        <h3>Product coherence</h3><p>Coherent products have predictable rules. Local exceptions weaken those rules and create future constraints. A customer-specific setting can block architectural simplification or make it impossible to explain why two accounts behave differently.</p>
        <p>Before accepting something as cheap, ask: who owns it? Where else must it work? How will people discover it? Which new states does it create? How can it be removed? Which precedent does it set? Which metric justifies keeping it?</p>
        <aside class="callout framework"><strong>The cheap-feature test.</strong> Add build + integration + operation + comprehension + maintenance + removal. If value does not cover the whole lifecycle, the short estimate is irrelevant.</aside>
        <aside class="callout error"><strong>Common mistake.</strong> Rejecting every small convenience in the name of purity. Coherence is not dogmatic minimalism. It is value greater than systemic cost.</aside>
        <aside class="callout takeaway"><strong>Takeaway.</strong> Development cost ends at launch. Product cost ends when the capability is removed.</aside>
        <p class="reflection"><strong>Reflection:</strong> which old feature does your team maintain without knowing who uses it or which outcome it protects?</p>` }
    ]
  }
];
